### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Nexuist** [dosco/minds#6]
Hey guys,

First I wanted to start by thanking the repo owner for including example scripts and samples in the README. However, I was wondering if there is any link to documentation that describes all the methods and classes available. This would be helpful in understanding how to leverage the package for novel workflows that have not been covered by the samples yet.

**Comment by dosco** [comment]
I have been meaning to generate and host the API docs online will handle it this week. However in the meanwhile just run `npm run doc` and it will generate and display the api docs.

**Comment by Nexuist** [comment]
Ooh, I didn't see there was a doc script yet. Thank you!

**Comment by dosco** [comment]
I have hosted the docs on github pages will update them further. https://dosco.github.io/minds/

**Comment by Nexuist** [comment]
Thank you for the update!
